# Xilytica - Preprocessing - Train - Test - Feature Scaling - Standardization - Hot Encoding

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# For on hot encoding with sklearn
from sklearn.preprocessing import OneHotEncoder

# Hot Encoding 

In [2]:
data = pd.read_csv('datasets/titanic/titanic.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# Survived is the target or the dependent variable
data_cat = pd.read_csv('datasets/titanic/titanic.csv', usecols=['Sex','Embarked','Cabin','Survived'])

In [7]:
data_cat.head()

Survived     Sex Cabin Embarked
0         0    male   NaN        S
1         1  female   C85        C
2         1  female   NaN        S
3         1  female  C123        S
4         0    male   NaN        S

In [8]:
# Getting only the 1st charcter of the Cabin Data
data_cat['Cabin']= data_cat['Cabin'].str[0]

In [9]:
data_cat.head()

Survived     Sex Cabin Embarked
0         0    male   NaN        S
1         1  female     C        C
2         1  female   NaN        S
3         1  female     C        S
4         0    male   NaN        S

# Encoding important
Just like imputation, all methods of categorical encoding should be performed over the training set, and then propagated to the test set.

Why?

Because these methods will "learn" patterns from the train data, and therefore you want to avoid leaking information and overfitting. But more importantly, because we don't know whether in future / live data, we will have all the categories present in the train data, or if there will be more or less categories. Therefore, we want to anticipate this uncertainty by setting the right processes right from the start. We want to create transformers that learn the categories from the train set, and used those learned categories to create the dummy variables in both train and test sets.

In [10]:
# Lets seprate data into training & test
X_train, X_test, y_train, y_test = train_test_split(
    data_cat[['Sex','Embarked','Cabin']], # Predictors or independent variables
    data_cat['Survived'],# Target
    test_size = 0.3, # Number of observations in the test set
    random_state = 0) # seed to ensure reproducibility 


X_train.shape, X_test.shape

((623, 3), (268, 3))

In [11]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 623 entries, 857 to 684
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Sex       623 non-null    object
 1   Embarked  621 non-null    object
 2   Cabin     152 non-null    object
dtypes: object(3)
memory usage: 19.5+ KB


# Finding out the cardinality in the predictors


In [12]:
X_train['Sex'].unique()
# Gender has two labels

array(['male', 'female'], dtype=object)

In [13]:
X_train['Embarked'].unique()
# Embarked has 3 labels & a missing value

array(['S', 'C', 'Q', nan], dtype=object)

In [14]:
X_train['Cabin'].unique()
# Cabin has 8 labels and missing data

array(['E', 'D', nan, 'B', 'C', 'A', 'F', 'G', 'T'], dtype=object)

# One hot encoding with Scikit-learn¶
### Advantages
quick
Creates the same number of features in train and test set
### Limitations
it returns a numpy array instead of a pandas dataframe
it does not return the variable names, therefore inconvenient for variable exploration

In [17]:
# Dense matrix - most of the values are not zero
# Sparse matrix - most of the values arezero
encoder = OneHotEncoder(
    categories='auto',# Learning categories in training set
    drop='first',# to return k-1, use False to return  k dummies
    sparse = False, # Returns numpy array else it will retrun sparse matrix
    handle_unknown='error'# To ignore those rare categories that are present in test set but not in training set
)


In [16]:
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')
 |  
 |  Encode categorical features as a one-hot numeric array.
 |  
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse``
 |  parameter)
 |  
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard ker

# fit method
In a nutshell: fitting is equal to training. Then, after it is trained, the model can be used to make predictions, usually with a .predict() method call.

To elaborate: Fitting your model to (i.e. using the .fit() method on) the training data is essentially the training part of the modeling process. It finds the coefficients for the equation specified via the algorithm being used (take for example umutto's linear regression example, above).

Then, for a classifier, you can classify incoming data points (from a test set, or otherwise) using the predict method. Or, in the case of regression, your model will interpolate/extrapolate when predict is used on incoming data points.

fitting means training. There is a fit function in ML, that is used for training of model using data examples. Fit function adjusts weights according to data values so that better accuracy can be achieved. After training, the model can be used for predictions, using .predict() method call.

In [18]:
encoder.fit(X_train.fillna('Missing'))

OneHotEncoder(drop='first', sparse=False)

In [19]:
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [21]:
# We observe the learned categories
encoder.categories_

[array(['female', 'male'], dtype=object),
 array(['C', 'Missing', 'Q', 'S'], dtype=object),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'Missing', 'T'], dtype=object)]

In [22]:
# Transform the training set
tmp = encoder.transform(X_train.fillna('Missing'))

In [25]:
pd.DataFrame(tmp).head()
0 - gender -  male
1,2,3 - Embarked Missing,Q,S
4,5,6,7,8,9,10,11 - Cabin

0    1    2    3    4    5    6    7    8    9    10   11
0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
3  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0

In [26]:
# we can now retrieve the feature names as follows:

encoder.get_feature_names()

array(['x0_male', 'x1_Missing', 'x1_Q', 'x1_S', 'x2_B', 'x2_C', 'x2_D',
       'x2_E', 'x2_F', 'x2_G', 'x2_Missing', 'x2_T'], dtype=object)

In [27]:
# we can go ahead and transfom the test set
# and then reconstitute it back to a pandas dataframe
# and add the feature names derived by OHE

tmp = encoder.transform(X_test.fillna('Missing'))

tmp = pd.DataFrame(tmp)
tmp.columns = encoder.get_feature_names()

tmp.head()

x0_male  x1_Missing  x1_Q  x1_S  x2_B  x2_C  x2_D  x2_E  x2_F  x2_G  \
0      1.0         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
1      1.0         0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
2      1.0         0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3      0.0         0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
4      0.0         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

   x2_Missing  x2_T  
0         1.0   0.0  
1         1.0   0.0  
2         1.0   0.0  
3         0.0   0.0  
4         1.0   0.0

# Feature Scaling 

### Standardization

In [29]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [36]:
# Loading the boston House Price Dataset
boston = load_boston()

In [37]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [38]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [52]:
print(boston.DESCR)

# Boston Price dataset
# The aim is to prdict the Median value of the houses
# MEDV Column in the dataset

# There are variables with characterstics about the home & the neighborhoods



.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [45]:
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [46]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [47]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [48]:
data = pd.DataFrame(boston.data, columns=boston.feature_names)

In [49]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [50]:
data['MEDV'] = boston.target

In [51]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [53]:
# To get an idea of feature magnitude

data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [54]:
# Mean is not centered at 0
# Std is not 1
# min and max values gives us range of magnitude

In [55]:
# When standardising the dataset, we need to first identify the mean & standard deviaiton of the variables.
# The parameters need to be learned from the train dataset stored and used to scale test & future data.
# SPliting teh data into train & test

In [57]:
X_train,X_test,y_train,y_test = train_test_split(data.drop('MEDV', axis = 1),
                                                data['MEDV'],
                                                test_size = 0.3,
                                                random_state =0 )

X_train.shape, X_test.shape

((354, 13), (152, 13))

In [58]:
# The StandardScaler from scikit learn removes the mean (mean = 0) & scales the data to unit variance (std = 1)
# It learns & stores the parameter needed for scaling. Thus its top choice for this feature scaling technique

# Downside of using this technique is - It will scale the entire dataset
# It returns the numpy array without the variable values

In [62]:
# Standardising With Sklearn

# setup the scaler
scaler = StandardScaler()

# Fit the scaler to train set, it will learn the parameters
# Will learn the mean & std of the training set variables
scaler.fit(X_train)

# transform the train & test sets
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [74]:
X_train_scaled

array([[-0.20735619, -0.49997924,  1.54801583, ...,  1.2272573 ,
         0.42454294,  3.10807269],
       [-0.38886492,  0.34677427, -0.58974728, ...,  0.05696346,
         0.40185312, -0.66643035],
       [-0.33573486, -0.49997924,  1.54801583, ...,  1.2272573 ,
         0.39846135,  0.63936662],
       ...,
       [-0.38450355, -0.49997924, -0.15303077, ..., -0.30312696,
         0.39659002, -0.30284441],
       [-0.37511786, -0.49997924, -0.59690657, ..., -0.25811566,
         0.37588849,  0.89967717],
       [-0.38592298, -0.49997924, -1.00641779, ..., -0.84326258,
         0.42454294,  0.31822262]])

In [79]:
X_train_scaled[:,0]

array([-0.20735619, -0.38886492, -0.33573486, -0.39485192, -0.39145561,
       -0.25485052, -0.38635456, -0.25253436,  1.41689551, -0.32612258,
       -0.39816191, -0.34710223, -0.40026467, -0.37370803, -0.36050763,
       -0.39725439,  0.14189864,  1.19901885, -0.40087847,  1.39845739,
        0.04014015, -0.24993648, -0.11745179,  1.73932276, -0.38128468,
       -0.36788527,  0.15448283, -0.39740424,  0.52676253,  4.11244485,
       -0.39849518, -0.13378115, -0.38207951, -0.37960271, -0.38743831,
       -0.40080414, -0.39588771,  0.2664758 ,  0.87677142, -0.30366836,
       -0.39624736, -0.37220588, -0.33780645, -0.39915694, -0.39836331,
       -0.02333948, -0.30784631, -0.39525592, -0.39756488, -0.30637174,
       -0.33857131, -0.39808638, -0.11735948, -0.24161895, -0.20400424,
       -0.38578391,  0.03780961, -0.18677934, -0.39572827, -0.34019453,
        1.32621547, -0.39735389, -0.37123123,  0.71697722, -0.36772943,
       -0.38889849,  0.63376234, -0.39933197,  3.03276014, -0.35

In [82]:
# Getting the mean & standard deviation of scaled features
# column 1st
X_train_scaled[:,0].mean(), X_train_scaled[:,0].std()

(-1.5053871520341106e-17, 1.0)

In [64]:
# Scaler stores the mean of the features, learned from train set
scaler.mean_

array([3.35828432e+00, 1.18093220e+01, 1.10787571e+01, 6.49717514e-02,
       5.56098305e-01, 6.30842655e+00, 6.89940678e+01, 3.76245876e+00,
       9.35310734e+00, 4.01782486e+02, 1.84734463e+01, 3.60601186e+02,
       1.24406497e+01])

In [66]:
X_train['CRIM'].mean()

3.3582843220339016

In [68]:
# Scaler stores teh standard deviation of the features learned from the set
scaler.scale_

array([8.34141658e+00, 2.36196246e+01, 6.98393565e+00, 2.46476009e-01,
       1.15437239e-01, 7.01016354e-01, 2.79987983e+01, 2.06473886e+00,
       8.65974217e+00, 1.70351284e+02, 2.22166426e+00, 8.55009244e+01,
       7.06848020e+00])

In [73]:
X_train['CRIM'].std()

8.353223258870699

In [83]:
# Let's transform the returned Numpy arrays to dataframes for the rest 

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [85]:
X_train_scaled.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.207356 -0.499979  1.548016 -0.263603  0.588213 -1.839367  1.107402   
1 -0.388865  0.346774 -0.589747 -0.263603 -0.797821  0.327487 -0.367661   
2 -0.335735 -0.499979  1.548016 -0.263603  0.588213  0.037907  1.043114   
3 -0.394852  2.463658 -1.265584 -0.263603 -1.352235  0.052172 -1.746292   
4 -0.391456 -0.499979  2.086394 -0.263603  0.215716 -0.495604  0.853820   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0 -1.125110 -0.618160  0.206735  1.227257  0.424543  3.108073  
1  0.075090 -0.733637 -1.049493  0.056963  0.401853 -0.666430  
2 -0.799984 -0.618160  0.206735  1.227257  0.398461  0.639367  
3  1.968937 -0.502683 -0.257013 -1.653466  0.089342 -1.056896  
4 -0.811511 -0.849114 -1.254951  0.282020  0.204545  0.776596

In [86]:
np.round(X_train.describe(),1)

CRIM     ZN  INDUS   CHAS    NOX     RM    AGE    DIS    RAD    TAX  \
count  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0   
mean     3.4   11.8   11.1    0.1    0.6    6.3   69.0    3.8    9.4  401.8   
std      8.4   23.7    7.0    0.2    0.1    0.7   28.0    2.1    8.7  170.6   
min      0.0    0.0    0.5    0.0    0.4    3.6    2.9    1.2    1.0  187.0   
25%      0.1    0.0    5.0    0.0    0.4    5.9   45.2    2.1    4.0  276.0   
50%      0.3    0.0    8.6    0.0    0.5    6.2   79.4    3.2    5.0  311.0   
75%      3.1   20.0   18.1    0.0    0.6    6.6   93.8    5.1   24.0  666.0   
max     89.0  100.0   27.7    1.0    0.9    8.8  100.0   12.1   24.0  711.0   

       PTRATIO      B  LSTAT  
count    354.0  354.0  354.0  
mean      18.5  360.6   12.4  
std        2.2   85.6    7.1  
min       12.6    0.3    1.7  
25%       17.4  376.1    6.7  
50%       19.1  391.6   11.2  
75%       20.2  395.7   16.7  
max       22.0  396.9   37.0

In [87]:
np.round(X_train_scaled.describe(),1)

CRIM     ZN  INDUS   CHAS    NOX     RM    AGE    DIS    RAD    TAX  \
count  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0  354.0   
mean     0.0    0.0   -0.0    0.0   -0.0   -0.0    0.0    0.0    0.0   -0.0   
std      1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0   
min     -0.4   -0.5   -1.5   -0.3   -1.5   -3.9   -2.4   -1.3   -1.0   -1.3   
25%     -0.4   -0.5   -0.9   -0.3   -0.9   -0.6   -0.9   -0.8   -0.6   -0.7   
50%     -0.4   -0.5   -0.4   -0.3   -0.2   -0.1    0.4   -0.3   -0.5   -0.5   
75%     -0.0    0.3    1.0   -0.3    0.6    0.5    0.9    0.6    1.7    1.6   
max     10.3    3.7    2.4    3.8    2.7    3.5    1.1    4.1    1.7    1.8   

       PTRATIO      B  LSTAT  
count    354.0  354.0  354.0  
mean       0.0   -0.0   -0.0  
std        1.0    1.0    1.0  
min       -2.6   -4.2   -1.5  
25%       -0.5    0.2   -0.8  
50%        0.3    0.4   -0.2  
75%        0.8    0.4    0.6  
max        1.6    0.4    3.5