In [2]:
data = pd.read_csv('C:/Users/Administrator/Class Notebooks/Datasets/SUV-data.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [4]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
data.sample(5)

Age  EstimatedSalary  Purchased
50    24            32000          0
182   32           117000          1
306   51           134000          0
8     25            33000          0
255   52            90000          1

In [6]:
data.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [9]:
data['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [11]:
data[['Age','EstimatedSalary','Purchased']].groupby('Purchased').mean()

Age  EstimatedSalary
Purchased                            
0          32.793774     60544.747082
1          46.391608     86272.727273

In [30]:
pd.pivot_table(data, index='Purchased',values = ('Age', 'EstimatedSalary'))

Age  EstimatedSalary
Purchased                            
0          32.793774     60544.747082
1          46.391608     86272.727273

In [31]:
# X = data[:,:-1].values
# y = data[:,-1].values

In [47]:
X = data.drop('Purchased', axis = 'columns')
y = data['Purchased']

In [48]:
X.shape, y.shape

((400, 2), (400,))

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.75, random_state = 101)

In [52]:
# Looking at 1st 5 rows
X_train.head()

Age  EstimatedSalary
39    27            31000
95    35            44000
109   38            80000
9     35            65000
224   35            60000

In [54]:
X_train.shape

(300, 2)

In [77]:
y_train

39     0
95     0
109    0
9      0
224    0
      ..
63     1
326    0
337    0
11     0
351    0
Name: Purchased, Length: 300, dtype: int64

In [55]:
X_test.head()

Age  EstimatedSalary
38    26            72000
387   39            71000
270   43           133000
181   31            71000
195   34            43000

In [68]:
y_test.head()

38     0
387    0
270    0
181    0
195    0
Name: Purchased, dtype: int64

In [56]:
X_test.shape

(100, 2)

In [57]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
# Values between +3 & -3
X_train[0:5,:]

array([[-1.03893527, -1.12434375],
       [-0.25900263, -0.73854922],
       [ 0.03347211,  0.32980486],
       [-0.25900263, -0.11534267],
       [-0.25900263, -0.26372518]])

In [62]:
# Values between +3 & -3
X_test[0:5,:]

array([[-1.13642685,  0.09239284],
       [ 0.13096369,  0.06271634],
       [ 0.52093001,  1.90265948],
       [-0.64896895,  0.06271634],
       [-0.35649421, -0.76822572]])

In [63]:
# Model Building
from sklearn.linear_model import LogisticRegression
# Bulding the model
lgr = LogisticRegression()
# Training the model
lgr.fit(X_train,y_train)


LogisticRegression()

In [71]:
# Predicting the Result
pred_01 = lgr.predict(sc.transform([[26,72000]]))

In [72]:
print(pred_01)

[0]


In [74]:
y_pred = lgr.predict(X_test)

y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [78]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.values.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]]


In [84]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [82]:
cm = confusion_matrix(y_test, y_pred)

In [83]:
cm

array([[57,  8],
       [11, 24]], dtype=int64)

In [85]:
accuracy_score(y_test, y_pred)

0.81

In [81]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86        65
           1       0.75      0.69      0.72        35

    accuracy                           0.81       100
   macro avg       0.79      0.78      0.79       100
weighted avg       0.81      0.81      0.81       100

